export const RACAS_CAO: string[] = [
  'SRD (vira-lata)',
  'Akita',
  'American Bully',
  'Beagle',
  'Bichon Frisé',
  'Border Collie',
  'Boxer',
  'Bulldog Francês',
  'Bulldog Inglês',
  'Cane Corso',
  'Cavalier King Charles',
  'Chihuahua',
  'Chow Chow',
  'Cocker Spaniel',
  'Dálmata',
  'Dachshund (salsicha)',
  'Doberman',
  'Fila Brasileiro',
  'Fox Paulistinha',
  'Golden Retriever',
  'Husky Siberiano',
  'Jack Russell Terrier',
  'Labrador Retriever',
  'Lhasa Apso',
  'Maltês',
  'Mastiff',
  'Pastor Alemão',
  'Pastor Australiano',
  'Pastor Belga',
  'Pinscher',
  'Pit Bull',
  'Poodle',
  'Pug',
  'Rottweiler',
  'São Bernardo',
  'Schnauzer',
  'Shar-pei',
  'Shih Tzu',
  'Spitz Alemão (Lulu da Pomerânia)',
  'Weimaraner',
  'Yorkshire Terrier',
  'Outra',
];

export const RACAS_GATO: string[] = [
  'SRD (vira-lata)',
  'Abissínio',
  'American Shorthair',
  'Angorá',
  'Azul Russo',
  'Bengal',
  'Birmanês',
  'Bombay',
  'British Shorthair',
  'Exótico',
  'Himalaio',
  'Maine Coon',
  'Munchkin',
  'Norueguês da Floresta',
  'Oriental',
  'Persa',
  'Ragdoll',
  'Savannah',
  'Scottish Fold',
  'Siamês',
  'Sphynx',
  'Outra',
];

export const TEMPERAMENTOS: string[] = [
  'Calmo',
  'Sociável',
  'Brincalhão',
  'Energético',
  'Apegado',
  'Independente',
  'Tímido',
  'Ansioso',
  'Medroso',
  'Territorial',
  'Vocal',
  'Bom com crianças',
  'Bom com outros pets',
  'Reativo com outros pets',
  'Reativo com pessoas',
];

export function racasPorEspecie(especie: string): string[] {
  return especie === 'gato' ? RACAS_GATO : RACAS_CAO;
}
